# This file was generated by GoReleaser. DO NOT EDIT.
class Jarl < Formula
  desc "Locate jar coordinates right from your terminal."
  homepage "https://github.com/devcsrj/jarl"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/devcsrj/jarl/releases/download/1.0.0/jarl_1.0.0_Darwin_x86_64.tar.gz"
    sha256 "53fdfaf1ef5a08e2e6bf370369ec679eaea1e69768a46847bc5c6d7e43908ac4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/devcsrj/jarl/releases/download/1.0.0/jarl_1.0.0_Linux_x86_64.tar.gz"
      sha256 "5ff029e15892216360d76dad2cb0861ef1f0a4ae724d7b698294623fb02fdd30"
    end
  end

  def install
    bin.install "jarl"
  end
end
